平日課題５：生年月日占いアプリ
ShunOmine/camp_weekday_task5 pull request #2
Opened 2019-03-06 06:48 UTC by ShunOmine

# 課題詳細
- アプリ名(ディレクトリ名)はcamp_weekday_task5です。
- コントローラとビューを作成して生年月日占いアプリを作成して下さい。
- URLに指定した値(8桁の数値)を使用して生年月日から占いを行います。
- URLは/fortunetelling/までは固定で、それ以降をパラメータで受け取る必要があります。
- params[XXX]で受け取った値は文字列として認識されるので、to_iメソッドを使用して数値に変換してから計算する必要があります。
- コントローラ名はfortunetellings、アクション名はshowで作成して下さい。
- common.rbも作成しています。
   - common.rb内にconstellationメソッドを定義しています。(生年月日から星座を表示するため)

# 課題リンク
[*平日課題５：生年月日占いアプリ*](https://interncamp.gitbook.io/ruby/exercises/week01/exercise05)

# 受け入れ基準
- [ ] 8桁の生年月日からあなたの誕生日は1994年4月7日です。のように表示できること。
- [ ] 本日(例として2月24日)が誕生日の場合、あなたの誕生日は1994年2月24日です。今日があなたの誕生日です。のように表示できること。
- [ ] 生年月日からあなたの星座は牡羊座です。のように正しい星座を表示できること。
- [ ] 生年月日からあなたは24歳です。のように正しい年齢を表示できること。
- [ ] 今日のあなたの運勢は大吉です。のように以下の中からランダムで運勢を表示できること。

#

2019-03-06 06:54 UTC, ShunOmine commented on app/controllers/concerns/common.rb
> +end
common.rb内に生年月日から星座を取得する
constellationメソッドを定義しました。

2019-03-06 07:00 UTC, ShunOmine commented on app/controllers/fortunetellings_controller.rb
> +end
fortunetellings_controller.rb内には
@birthday = params[:birthday] で値を取得しています。
@birth で@birthdayで取得した値を分割して年、月、日を表示
@birtt_today で今日の日付と入力された値が一致するか確認
@age で歳を計算
@fortune  = fortune.sample で配列からランダムに取り出す。
@constellation は星座を調べる。(common.rb内に詳しいコードは記述)

2019-03-06 07:01 UTC, ShunOmine commented on app/views/fortunetellings/show.html.erb
> +<p>今日のあなたの運勢は<%= @fortune %>です。</p>
それぞれ出た値を表示。

2019-03-06 07:03 UTC, ShunOmine commented on config/routes.rb
>  end
urlは[*平日課題５：生年月日占いアプリ*](https://interncamp.gitbook.io/ruby/exercises/week01/exercise05)で指定された通りに表示

2019-03-07 09:01 UTC, N-Ryo requested changes
リファクタリングのコメントをいくつか残しました。
確認お願いします！

2019-03-07 09:01 UTC, N-Ryo commented on .gitignore
> +/vendor/bundle/
上にも/vendoe/bundleがあったので、こちらは消していてもいいかもしれないですね！

2019-03-07 09:01 UTC, N-Ryo commented on app/controllers/concerns/common.rb
> +    names = %w(山羊座 水瓶座 魚座 牡羊座 牡牛座 双子座 蟹座 獅子座 乙女座 天秤座 蠍座 射手座)
「座」が重複しているので、Viewで揃えるのもありかな、と思います！

2019-03-07 09:01 UTC, N-Ryo commented on app/controllers/fortunetellings_controller.rb
> +    @birth_today = "今日があなたの誕生日です。" if @birthday[4, 4].to_i == Date.today.strftime("%m%d").to_i
ifの両辺にto_iメソッドがいるので、これを抜いても正しく動作すると思います。
冗長な記述になると思うので、動作を確認した上でリファクタリングすることをオススメします！

2019-03-07 09:01 UTC, N-Ryo commented on app/controllers/fortunetellings_controller.rb
> +    @fortune = fortune.sample
ローカル変数fortuneに一度入れなくても、配列に直接sampleメソッドを突っ込んでも動作します。
1行にまとめてしまいましょう！

2019-03-07 09:01 UTC, N-Ryo commented on log/development.log
> +Started GET "/" for 127.0.0.1 at 2019-03-06 14:02:52 +0900
logファイルは基本的に.gitignoreでpushされないようにしましょう！
rails serverで実行した情報などは含まれていて欲しくない&重要な情報が入っているとやばいので、対応お願いします！

2019-03-13 02:26 UTC, koooosuke commented
LGTMです！

2019-03-27 05:31 UTC, merged